### ISSUE TITLE
Can't find a pretrained model

### ISSUE THREAD

**Issue by Fordacre** [bcmi/SLBR-Visible-Watermark-Removal#1]
Hi Li. Thanks for your work, but I can't find a pretrained model in the code. Can you provide one? Besides, is there a demo script for custom images?

**Comment by jimleungjing** [comment]
Hi, thanks for your attention! We will release the pretrained model  and provide a demo test file for custom images in next month.

**Comment by nulam** [comment]
Hello, how is the progress on the pretrained weights being released?

**Comment by jimleungjing** [comment]
Hi, we've released a model trained on CLWD. Have a try :)
