### ISSUE TITLE
请教一个环境问题

### ISSUE THREAD

**Issue by iamluodong** [bcmi/SLBR-Visible-Watermark-Removal#11]
初入这个领域，不懂的地方是在太多，现在环境倒是安好了，测试了好几个python 版本，目前来看3.7好像比较适合。现在卡在我们依赖的库太旧了。torch==1.6.0 我看官方已经不维护了，改为1.7 ，又出现
ERROR: torch has an invalid wheel, torch has an invalid wheel, .dist-info directory not found 这样的问题。
不只是否有时间否更新一下依赖库？

**Comment by jimleungjing** [comment]
你试试别的pytorch版本看看

**Comment by iamluodong** [comment]
勉强跑起来了，不过内存太低，训练出错，不止咱这个有调 batch size 的地方吗？

**Comment by jimleungjing** [comment]
请参考scripts/train.sh 里面batch_size的参数

**Comment by iamluodong** [comment]
好的
