### ISSUE TITLE
测试时，图像必须resize成长宽一致吗？

### ISSUE THREAD

**Issue by YangShuguang** [bcmi/SLBR-Visible-Watermark-Removal#12]

**Comment by jimleungjing** [comment]
测试图片需要与训练图片尺寸一致，否则会有性能衰退；我们的预训练模型是在256x256图片训练的，所以测试时需要对齐；

**Comment by YangShuguang** [comment]
> 测试图片需要与训练图片尺寸一致，否则会有性能衰退；我们的预训练模型是在256x256图片训练的，所以测试时需要对齐；

我测试的时候，把长宽设置的不同会报tensor维度不一致的错误，如果抛开性能衰退不谈，要把长宽设置的不一样，需要大改网络吗？

**Comment by jimleungjing** [comment]
长宽不一样需要自己设计好卷积核kernel_size/stride/padding，保证下采样的tensor高与宽能与上采样对应层的tensor对齐，因为我们的模型设计采用了类似UNet的跳跃链接结构

**Comment by 18106574249** [comment]
作者，您好，1000x1000 的图片,把参数改成1000，其他对应的mask，alpha都改成1000后，可以直接运行模型吗？还是需要更改里面相应的结构呢，盼回复，谢谢！

**Comment by jimleungjing** [comment]
> 作者，您好，1000x1000 的图片,把参数改成1000，其他对应的mask，alpha都改成1000后，可以直接运行模型吗？还是需要更改里面相应的结构呢，盼回复，谢谢！

可以运行，需要注意resulotion 增长后带来的gpu开销问题，可能需要你自己减小batch size 或者裁剪网络
