### ISSUE TITLE
Question about the optimizer

### ISSUE THREAD

**Issue by cvbird** [bcmi/SLBR-Visible-Watermark-Removal#13]
Hi, thanks for your excellent work.

I am puzzled about the settings of optimizers as follows:
`def set_optimizers(self):
        self.optimizer_encoder = torch.optim.Adam(self.encoder.parameters(), lr=self.args.lr)
        self.optimizer_image = torch.optim.Adam(self.coarse_decoder.parameters(), lr=self.args.lr)
        
        if self.refinement is not None:
            self.optimizer_refine = torch.optim.Adam(self.refinement.parameters(), lr=self.args.lr)
        
        if self.shared != 0:
            self.optimizer_shared = torch.optim.Adam(self.shared_decoder.parameters(), lr=self.args.lr)`

As can be seen, different optimizers are set to different components. However, the learning rates are the same. I wonder is there any difference to set only one optimizer to the parameters of SLBR model.

Thank you very much and looking forward your replies.

**Comment by jimleungjing** [comment]
In this case, you can set only one optimizer for SLBR model since learning rates are same.
