### ISSUE TITLE
Question about the cost of training

### ISSUE THREAD

**Issue by lianchengmingjue** [bcmi/SLBR-Visible-Watermark-Removal#14]
Thanks for your impressive work. I have some question about the cost of training.
I used 4 Titan Xp, batchsize is set as 8, train on CLWD dataset. It seems to take 150 hours to complete the training, namely 600 GPU hour. What is your hardware environment during training?
Or maybe I got something wrong.
Looking forward to your reply.

**Comment by jimleungjing** [comment]
We use 1 Titan RTX in the experiments, and it takes about 4-5 days to complete the training

**Comment by lianchengmingjue** [comment]
Thanks for your kindness reply. I only have TITAN XP available. SJTU 666.

**Comment by ccuted** [comment]
> 
您好！想请问您训练了多少个epoch?
