### ISSUE TITLE
如果能放在kaggle上就好了，可以直接运行测试

### ISSUE THREAD

**Issue by gg22mm** [bcmi/SLBR-Visible-Watermark-Removal#16]

**Comment by gg22mm** [comment]
太不靠谱了：

Bad key verbose.fileo in file d:\Anaconda3\envs\sy\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 476 ('verbose.fileo  : sys.stdout  # a log filename, sys.stdout or sys.stderr')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.4/matplotlibrc.template
or from the matplotlib source distribution
In d:\Anaconda3\envs\sy\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In d:\Anaconda3\envs\sy\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In d:\Anaconda3\envs\sy\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In d:\Anaconda3\envs\sy\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In d:\Anaconda3\envs\sy\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In d:\Anaconda3\envs\sy\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In d:\Anaconda3\envs\sy\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The animation.avconv_path rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In d:\Anaconda3\envs\sy\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The animation.avconv_args rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
==================================== WaterMark Removal =============================================
==> Start Time                                        : Wed Jun 15 09:09:34 2022
==> USE GPU                                           : 0
==================================== Stable Parameters =============================================
==> epochs                                            : 100(100)
==> schedule                                          : 65(65)
==> lr                                                : 1e-3(1e-3)
==> gpu_id                                            : 0(0)
==> checkpoint                                        : E:/wll/phpsys/WWW/start/dzjk/txsb/api/resnet/pytorch/watermark/SLBR-Visible-Watermark-Removal/media/sda/Watermark(E:/wll/phpsys/WWW/start/dzjk/txsb/api/resnet/pytorch/watermark/SLBR-Visible-Watermark-Removal/media/sda/Watermark)
==> dataset_dir                                       : E:/wll/phpsys/WWW/start/dzjk/txsb/api/resnet/pytorch/watermark/SLBR-Visible-Watermark-Removal/media/sda/datasets/Watermark/CLWD(E:/wll/phpsys/WWW/start/dzjk/txsb/api/resnet/pytorch/watermark/SLBR-Visible-Watermark-Removal/media/sda/datasets/Watermark/CLWD)
==> nets                                              : slbr(slbr)
==> sltype                                            : vggx(vggx)
==> mask_mode                                         : res(res)
==> lambda_content                                    : 2.5e-1(2.5e-1)
==> lambda_style                                      : 2.5e-1(2.5e-1)
==> lambda_primary                                    : 0.01(0.01)
==> masked                                            : 1(1)
==> loss_type                                         : hybrid(hybrid)
==> models                                            : slbr(slbr)
==> preprocess                                        : resize(resize)
==> name                                              : slbr_v1(slbr_v1)
==> dataset                                           : CLWD(CLWD)
==================================== Changed Parameters =============================================
==> lambda_l1                                         : 2(2)
==> input_size                                        : 256(256)
==> crop_size                                         : 256(256)
==> train_batch                                       : 8(8)
==> test_batch                                        : 1(1)
==> k_center                                          : 2(2)
==> k_refine                                          : 3(3)
==> k_skip_stage                                      : 3(3)
==================================== Start Init Model  ===============================================
____ Namespace(checkpoint='E:/wll/phpsys/WWW/start/dzjk/txsb/api/resnet/pytorch/watermark/SLBR-Visible-Watermark-Removal/media/sda/Watermark', crop_size=256, dataset='clwd', dataset_dir='E:/wll/phpsys/WWW/start/dzjk/txsb/api/resnet/pytorch/watermark/SLBR-Visible-Watermark-Removal/media/sda/datasets/Watermark/CLWD', epochs=100, gpu_id='0', input_size=256, k_center=2, k_refine=3, k_skip_stage=3, lambda_content='2.5e-1', lambda_l1=2, lambda_primary='0.01', lambda_style='2.5e-1', loss_type='hybrid', lr='1e-3', mask_mode='res', masked=True, models='slbr', name='slbr_v1', nets='slbr', preprocess='resize', schedule=65, seed=1, sltype='vggx', test_batch=1, train_batch=8)
Traceback (most recent call last):
  File "train.py", line 123, in <module>
    main(args)
  File "train.py", line 30, in main
    print(dataset_func('train',args))
  File "E:\wll\phpsys\WWW\start\dzjk\txsb\api\resnet\pytorch\watermark\SLBR-Visible-Watermark-Removal\datasets\clwd_dataset.py", line 37, in __init__
    additional_targets={'J':'image', 'I':'image', 'watermark':'image', 'mask':'mask', 'alpha':'mask' }) #,
  File "E:\wll\phpsys\WWW\start\dzjk\txsb\api\resnet\pytorch\watermark\SLBR-Visible-Watermark-Removal\datasets\base_dataset.py", line 110, in get_transform
    if not opt.no_flip:
AttributeError: 'Namespace' object has no attribute 'no_flip'

如果能放在kaggle上可以直接运行起来就火了， 但是这样让人很是苦恼，放弃了，还是去研究我的： noise2noise_pytoch 去了

**Comment by FlotingDream** [comment]
Kaggle train code something like this, work fine for me.

`

!git clone https://github.com/bcmi/SLBR-Visible-Watermark-Removal.git
!mv ./SLBR-Visible-Watermark-Removal/* .

!pip install progress
!pip install scikit-image==0.17.2
!pip install tensorboardX
!pip install albumentations==0.4.5

K_CENTER=2
K_REFINE=3
K_SKIP=3
MASK_MODE='res' #'cat'

L1_LOSS=2
CONTENT_LOSS=2.5e-1
STYLE_LOSS=2.5e-1
PRIMARY_LOSS=0.01
IOU_LOSS=0.25 

INPUT_SIZE=256
DATASET='CLWD'
NAME='slbr_v1'

!python -u train.py \
 --epochs 100 \
 --schedule 65 \
 --lr 1e-3 \
 --gpu_id 0 \
 --checkpoint   ./checkpoint \ 
 --dataset_dir ../input/watermark \
 --nets slbr  \
 --sltype vggx \
 --mask_mode {MASK_MODE} \
 --lambda_content {CONTENT_LOSS} \
 --lambda_style {STYLE_LOSS} \
 --lambda_iou {IOU_LOSS} \
 --lambda_l1 {L1_LOSS} \
 --lambda_primary ${PRIMARY_LOSS} \
 --masked True \
 --loss-type hybrid \
 --models slbr \
  --input-size {INPUT_SIZE} \
 --crop_size {INPUT_SIZE} \
 --train-batch 8 \
 --test-batch 1 \
 --preprocess resize \
 --name {NAME} \
 --k_center {K_CENTER} \
 --dataset {DATASET} \
 --use_refine \
 --k_refine {K_REFINE} \
 --k_skip_stage {K_SKIP} \
  --start-epoch 70 \
  --resume ./checkpoint/{NAME}/model_best.pth.tar

`
