### ISSUE TITLE
About BVMR

### ISSUE THREAD

**Issue by Haoru** [bcmi/SLBR-Visible-Watermark-Removal#18]
您好，请问您能提供一下关于BVMR方法在LVW和CLWD数据集上的测试结果吗？

**Comment by jimleungjing** [comment]
我们的论文给出了BVMR在LVW和CLWD上的各项量化指标；BVMR模型可以裁剪 SplitNet网络，训练获得

**Comment by Haoru** [comment]
请问如何裁剪 SplitNet网络，获取BVMR的训练模型？

**Comment by Haoru** [comment]
另外，请问您尝试过SplitNet在LVW和CLWD数据集上训练和测试吗？

**Comment by jimleungjing** [comment]
去掉SplitNet Refinement, 去掉Coarse Stage里的channel attention，剩下的细节比对这BVMR 论文
