### ISSUE TITLE
Dataset Source

### ISSUE THREAD

**Issue by jaytimbadia** [bcmi/SLBR-Visible-Watermark-Removal#19]
Hey, 

I have contacted the authors of LVW for the dataset, but he has not responded till now. 
Can you please provide me with the dataset? My task is pending and it would be really great if you can provide me with the dataset.

Thank you!

**Comment by jimleungjing** [comment]
Thanks for your attention! We provide an alternative link in the ```Dataset``` section of https://github.com/bcmi/Awesome-Visible-Watermark-Removal.
