### ISSUE TITLE
Question about the mask in dataset.

### ISSUE THREAD

**Issue by star-ice** [bcmi/SLBR-Visible-Watermark-Removal#21]
Is there any influence if the masks in the dataset are not accurate?

For example, I detected the watermarked area with YOLO, so the mask was generated as white squares. If I put these kinds of masks in the training process, will the result still be good or not?

**Comment by jimleungjing** [comment]
I'm not sure whether it works, and you can try it. I think that accurate mask will be better for watermark removal since accurate mask provides more edge details than square mask.  If only square masks are available, this task will fall into the scope of  implicit watermark removal. And the model will be required to  be  aware of the pixels that are not belonging to watermark, which is harder than explicit watermark removal task.

**Comment by star-ice** [comment]
Thanks for your reply. I've trained the model with unclear masks and it works. While with some backgrounds full of letters or complex patterns, the model could not recover the background nicely. 

There is still another question. I utilised your model in the task of removing stamps from documents, and I also built the explicit masks with stamps in the training task, while black stamps and other stamps that have the same colour as the documents were not able to remove. Is there any method to improve the result? Thanks for your help.

The stamps on the documents are as follows:
![image](https://user-images.githubusercontent.com/30042959/194203770-a53bf6a0-e38e-46e8-91a7-b7e53a8c1406.png)
![image](https://user-images.githubusercontent.com/30042959/194203844-1c8e986f-2aaf-4715-8e5d-420ae0332c08.png)
![image](https://user-images.githubusercontent.com/30042959/194203988-3b7eff1a-d7a5-4998-9f06-41df0fe1f0d1.png)
![image](https://user-images.githubusercontent.com/30042959/194204083-b01717f3-44b4-4a5f-ac47-f2bae1bd2a26.png)

**Comment by jimleungjing** [comment]
I recommend you to build two models for gray stamps and color stamps respectively. Gray stamps are more difficult to remove since the background is full of gray and black letters or other patterns, and you can make more data augmentation or try the removal model with scene text regonition model.

**Comment by star-ice** [comment]
Thanks for your answer! I'll try your idea and check the performance later. That's quite helpful.

**Comment by huakngping** [comment]
> Thanks for your reply. I've trained the model with unclear masks and it works. While with some backgrounds full of letters or complex patterns, the model could not recover the background nicely.
> 
> There is still another question. I utilised your model in the task of removing stamps from documents, and I also built the explicit masks with stamps in the training task, while black stamps and other stamps that have the same colour as the documents were not able to remove. Is there any method to improve the result? Thanks for your help.
> 
> The stamps on the documents are as follows: ![image](https://user-images.githubusercontent.com/30042959/194203770-a53bf6a0-e38e-46e8-91a7-b7e53a8c1406.png) ![image](https://user-images.githubusercontent.com/30042959/194203844-1c8e986f-2aaf-4715-8e5d-420ae0332c08.png) ![image](https://user-images.githubusercontent.com/30042959/194203988-3b7eff1a-d7a5-4998-9f06-41df0fe1f0d1.png) ![image](https://user-images.githubusercontent.com/30042959/194204083-b01717f3-44b4-4a5f-ac47-f2bae1bd2a26.png)

你好，我想问一下，你这个印章印记的去除效果还蛮好的，尤其是印章印记灰度图的提取，想了解一下你是修改模型哪一块的参数呢？

**Comment by star-ice** [comment]
> 

你好，我是用了默认的参数训练的，需要用数据增强增加一些灰度样本，并且训练图像的大小也尽可能贴近默认参数的输入图像大小。

**Comment by huakngping** [comment]
> > 
> 
> 你好，我是用了默认的参数训练的，需要用数据增强增加一些灰度样本，并且训练图像的大小也尽可能贴近默认参数的输入图像大小。

您好，我想再问一下，就是我使用这个模型进行训练的时候，最后test.py输出的测试结果中
![Uploading 微信图片_20230802155344.png…]()
水印提取的很差，包含着很多的背景信息。就像这样： 想请教一下，您有遇到这种情况吗？

**Comment by huakngping** [comment]
你好，我是用了默认的参数训练的，需要用数据增强增加一些灰度样本，并且训练图像的大小也尽可能贴近默认参数的输入图像大小。

您好，我想再问一下，就是我使用这个模型进行训练的时候，最后test.py输出的测试结果中
![Uploading 微信图片_20230802155344.png…]()

水印提取的很差，包含着很多的背景信息。就像这样： 想请教一下，您有遇到这种情况吗？

**Comment by huakngping** [comment]
你好，我是用了默认的参数训练的，需要用数据增强增加一些灰度样本，并且训练图像的大小也尽可能贴近默认参数的输入图像大小。

您好，我想再问一下，就是我使用这个模型进行训练的时候，最后test.py输出的测试结果中水印提取的很差，包含着很多的背景信息。就像这样： 
<img width="643" alt="微信图片_20230802155344" src="https://github.com/bcmi/SLBR-Visible-Watermark-Removal/assets/98293596/030ce27e-c736-442f-8015-6fc4554d07e0">

想请教一下，您有遇到这种情况吗？

**Comment by star-ice** [comment]
会不会是训练轮数不够导致的？看mask提取效果是不错的。
最后一个图片是什么呢？
还有就是在测试的时候也尽量把图片的预处理做的和训练时一致。
