### ISSUE TITLE
test_custom

### ISSUE THREAD

**Issue by najmemhmdb** [bcmi/SLBR-Visible-Watermark-Removal#22]
When I run test_custom.py file on my own images, I get different results in consequent executions which is so strange. Also, results are so bad. My question is are there any parameters that I must change to get better results? 

Thank you!

**Comment by maryam95hallal** [comment]
Greetings, @najmemhmdb. Did you figure out the issue?
I used Pix2Pix to test it for the identical purpose, and while the training phase produced fine images, the inference phase produced strange artifacts (the generated images contained additional watermark shapes as if the network trained to generate watermarked images.)
I'm currently looking for a different network to complete the project; any assistance is greatly appreciated.
