### ISSUE TITLE
CLWD测试集中没有Watermark文件夹

### ISSUE THREAD

**Issue by Septend-fun** [bcmi/SLBR-Visible-Watermark-Removal#23]
作者您好，我在运行测试脚本script/test.sh时，使用CLWD测试集，遇到以下错误：
/tmp/pip-build-c8_36uuo/opencv-python-headless/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/home/ubuntu/sda/datasets/Watermark/CLWD/test/Watermark/2235.png'): can't open/read file: check file path/integrity
查看后发现确实缺少sda/datasets/Watermark/CLWD/test/Watermark文件夹，只有
Mask  
Watermarked_image 
Watermark_free_image
这三个文件夹，麻烦问下是需要生成Watermark文件夹吗？有具体的脚本吗？

**Comment by Septend-fun** [comment]
resolved

**Comment by Septend-fun** [comment]
close

**Comment by beanduck** [comment]
> 作者您好，我在运行测试脚本script/test.sh时，使用CLWD测试集，遇到以下错误： /tmp/pip-build-c8_36uuo/opencv-python-headless/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/home/ubuntu/sda/datasets/Watermark/CLWD/test/Watermark/2235.png'): can't open/read file: check file path/integrity 查看后发现确实缺少sda/datasets/Watermark/CLWD/test/Watermark文件夹，只有 Mask Watermarked_image Watermark_free_image 这三个文件夹，麻烦问下是需要生成Watermark文件夹吗？有具体的脚本吗？

您好，请问这个问题您解决了吗，我也有相同的疑惑呢，test文件夹缺少watermark文件，所以报错了

**Comment by jimleungjing** [comment]
> > 作者您好，我在运行测试脚本script/test.sh时，使用CLWD测试集，遇到以下错误： /tmp/pip-build-c8_36uuo/opencv-python-headless/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/home/ubuntu/sda/datasets/Watermark/CLWD/test/Watermark/2235.png'): can't open/read file: check file path/integrity 查看后发现确实缺少sda/datasets/Watermark/CLWD/test/Watermark文件夹，只有 Mask Watermarked_image Watermark_free_image 这三个文件夹，麻烦问下是需要生成Watermark文件夹吗？有具体的脚本吗？
> 
> 您好，请问这个问题您解决了吗，我也有相同的疑惑呢，test文件夹缺少watermark文件，所以报错了

可以自行修改测试文件的dataloader，我们的模型不会输出watermark，训练和测试都不需要watermark；CLWD数据集提供watermark是因为WDNet模型需要训练时预测watermark
