### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by angel-yi** [bcmi/SLBR-Visible-Watermark-Removal#24]
作者您好，我想请教一下要训练高分辨率去水印的话需要修改哪些地方，train.sh里面的INPUT_SIZE吗，网络模型能支持多大分辨率的，我看您训练与测试都是256的图像，我想做640、1024大小的去水印

**Comment by jimleungjing** [comment]
修改INPUT_SIZE，同时注意剪裁网络，大分辨率会带来显存不足的问题

**Comment by angel-yi** [comment]
确实，我是16G显存，640px就满了，1024的上不去，还得想办法
