### ISSUE TITLE
Inference and Training with Images of variable sizes

### ISSUE THREAD

**Issue by javierquincke** [bcmi/SLBR-Visible-Watermark-Removal#30]
Thank you for the excellent work done on this repository.

I would like to train a model (SLBR) from scratch using images of variable sizes (1200x1200, 1200x800, 1000x1000 etc.), my goal is to be able to return the image with the watermark removed in the same quality of the original image.

Do you have any recommendations on how to achieve this?

**Comment by jimleungjing** [comment]
1. It depends on your demand of the inference quality. If you want to infer the max size without any lost,  it is better to the resize the low resolution to the max resolution of your training set, and here it is 1200x1200. This way can ensure the sucess of backforward propagation. But to remember, the more high resolution you train, the more GPU memory it needs. 

2. If there are various sizes, including low(x<=256), middle(256<x<768), high resolution(x>=768), it is better to categorize the training set by size and train different models. You can also learn other high-resolution image generation methods, such as _Deep Back-Projection Networks For Super-Resolution_.

**Comment by javierquincke** [comment]
the model can handle training with non square images? such as 1200x800?

**Comment by jimleungjing** [comment]
> the model can handle training with non square images? such as 1200x800?

Sure. You can resize the non square images to squre images when training. Otherwise, you have to make changes to convolution kernels. Because every downsampling and upsampling will change the width and length of feature maps.
