### ISSUE TITLE
Color space changes

### ISSUE THREAD

**Issue by ChristianMeli** [bcmi/SLBR-Visible-Watermark-Removal#33]
Hello again, thank you for your support.

I want to ask why are there color space changes when loading the data, [for the CLWD dataset](https://github.com/bcmi/SLBR-Visible-Watermark-Removal/blob/47c665f1855ab6624cd52b28cefa797a9c8b96f7/datasets/clwd_dataset.py#L65) and when doing inference with [test_custom.py](https://github.com/bcmi/SLBR-Visible-Watermark-Removal/blob/22eb0ae88185b352a9e4ea0b9fb685c214f08f61/test_custom.py#L53)

Does it matter **to the model** the color space used? In that case, which one should you use.

I notice this when using your checkpoint for doing inference on my images. I could work around it just changing back the color space after applying the model.

**Comment by jimleungjing** [comment]
It is important to kepp the consistency between training and inference stage no matter what color space you use. The color space transformation is attributed to my history code. I used to load a pretrained ResNet-50 as encoder, so I have to change the color space to meet the request of pretrained parameters .

**Comment by ChristianMeli** [comment]
Ok, understood. So it's all good as long as you keep it consistent. Thanks!
