### ISSUE TITLE
How to train a watermark removal model on two datasets simultaneously

### ISSUE THREAD

**Issue by ccuted** [bcmi/SLBR-Visible-Watermark-Removal#35]
Hello！ Thank you very much for your tremendous contribution.
 I noticed that your code is trained on two datasets separately. I would like to try to train a model that can run on both datasets simultaneously, but I encountered difficulties. As far as I know, it is possible to merge the two datasets, but due to issues with image size and format, it may not be feasible. Therefore, I would like to ask if you have a better solution? Looking forward to your reply!

**Comment by jimleungjing** [comment]
You can unify the image size. For example, setting as 256x256 or 512x512 for two datasets in dataloader. Besides, you should append another loss or input condition to classify the grayscale and colorful watermark, and I believe it will benefit for the model learning from two types of dataset.

**Comment by ccuted** [comment]
好的，感谢您的回答。我还有几个问题想问您：
1.我在训练模型的时候发现水印预测效果很差，不知道从哪里入手去改善模型效果；
2.我发现我训练模型的时候40个epoch的效果最好，甚至比90个epoch的效果还要好,应当是过拟合了，正通过调参等操作来实现改变，请问您有比较好的建议嘛？
3.测试的时候我发现，psnr值一直没有显著提升，仅仅达到了19左右
4.我看到您在回答其他人提出的问题时涉及到了beta参数，请问在代码中具体指的是哪个参数呢？
