### ISSUE TITLE
test_custom.py error

### ISSUE THREAD

**Issue by luliloveshe** [bcmi/SLBR-Visible-Watermark-Removal#6]
import scripts.datasets as datasets
import scripts.machines as machines

can not find  “scripts.datasets” and  “scripts.machines”

**Comment by jimleungjing** [comment]
I just fixed it. Try and test the new code.

**Comment by luliloveshe** [comment]
运行成功了，感谢。使用提供的预训练模型进行水印去除，效果一般，可能还需要调试一下。后续会把去水印的测试效果发上来

**Comment by luliloveshe** [comment]
一批图片 尺寸大小不一致， 我设置的crop_size=512. 那么出来的图片都是512， 但是不设置又会报错。请问怎样保持原图尺寸呢

**Comment by jimleungjing** [comment]
> 一批图片 尺寸大小不一致， 我设置的crop_size=512. 那么出来的图片都是512， 但是不设置又会报错。请问怎样保持原图尺寸呢

可以记录原始图片大小，输入至神经网络时resize至训练时的图片大小，最后再resize回原始图片大小

**Comment by luliloveshe** [comment]
![slbrerr](https://user-images.githubusercontent.com/32316248/148504731-f8bf3c99-74e7-4aac-9bbc-5f98c3f7cd62.png)

按照上面，去完水印保存前图片resize回原始尺寸，但是变模糊了

**Comment by jimleungjing** [comment]
> ![slbrerr](https://user-images.githubusercontent.com/32316248/148504731-f8bf3c99-74e7-4aac-9bbc-5f98c3f7cd62.png)
> 
> 按照上面，去完水印保存前图片resize回原始尺寸，但是变模糊了

原始尺寸远大于训练时的尺寸由于图像插值会引入肉眼可见的模糊；建议自己构造数据集微调，使得原始尺寸与训练尺寸大致相当。

**Comment by luliloveshe** [comment]
现在去除之后 会有淡淡的印记 仔细辨认还是能看出一些。怎样获取抠出来的水印包含矩形框呢

**Comment by luliloveshe** [comment]
![矩形](https://user-images.githubusercontent.com/32316248/148863012-fa1d6757-afac-4e92-aaf8-97b09d4dba32.png)
抠出的水印图以及包围矩形
