### ISSUE TITLE
bad performance or wrong operation?

### ISSUE THREAD

**Issue by Breezewrf** [bcmi/SLBR-Visible-Watermark-Removal#7]
It's a pity to see such output, I don't know if there is a problem with the operation, please don't hesitate to enlighten me, thanks a lot
（with the code test_custom.py）
![image](https://user-images.githubusercontent.com/53564343/150824427-eefa22d6-7ba6-4220-ae94-a361d2bc04f3.png)

**Comment by jimleungjing** [comment]
Have you loaded the pretained model? It seems that the model is assigned with random weights.

**Comment by Breezewrf** [comment]
> Have you loaded the pretained model? It seems that the model is assigned with random weights.

glad to receive your reply, thank you so much, the problem has been solved！
