### ISSUE TITLE
Inference Code

### ISSUE THREAD

**Issue by atharvjairath** [bcmi/SLBR-Visible-Watermark-Removal#8]
Hi, Could you please add inference code for this model, for us to try on? Thanks!

**Comment by jimleungjing** [comment]
Hi, we provide an inference code named test_custom.py, and you can further tailor it.

**Comment by atharvjairath** [comment]
@jimleungjing Thanks!

**Comment by atharvjairath** [comment]
Hi, The code is working fine, Thanks for that. I have one question and it would be great if you can suggest to me:
1. I trained the model on 512X512 size, now If I want to infer the model using the test_custom.py file, on Image of different size (let's suppose 900X600), the code returns cropped img depending on the fixed value I set, but if I comment the line
```python 
def preprocess(file_path, img_size=512):
    img_J = cv2.imread(file_path)
    assert img_J is not None, "NoneType"
    h,w,_ = img_J.shape
    img_J = cv2.cvtColor(img_J, cv2.COLOR_BGR2RGB).astype(np.float)/255.
    img_J = torch.from_numpy(img_J.transpose(2,0,1)[np.newaxis,...]) #[1,C,H,W]
    # img_J = F.interpolate(img_J, size=(img_size, img_size), mode='bilinear') 
    
    return img_J 
```
It gives an error: `RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 74 but got size 75 for tensor number 1 in the list`
How can I fix that?
In order to fix the above error, we need to record the size and then interpolate it back to its original size, which will reduce the image quality. Do you have any workaround for that?

**Comment by atharvjairath** [comment]
on further inspection, I got to know this is caused due to UpConv and DownConv, it needs inputs to be a multiple of 8.

**Comment by jimleungjing** [comment]
> on further inspection, I got to know this is caused due to UpConv and DownConv, it needs inputs to be a multiple of 8.

That's right. 

> Do you have any workaround for that? 

You can train the model with different sizes of image, so that the model could be more robust. Besides, you can train various models with different resolution, i.e., one model for low resolution (128x128 - 512x512), another for high resolution ( 768x768 - 1536x1536).

**Comment by atharvjairath** [comment]
> You can train the model with different sizes of images so that the model could be more robust. Besides, you can train various models with different resolutions, i.e., one model for low resolution (128x128 - 512x512), another for high resolution ( 768x768 - 1536x1536).

Sure, I also believe this is the right approach. Thanks for suggesting in a short time.
